(() => {
  "use strict";
  const cfg = window.PLAYRUSH_CONFIG || {};
  const API = String(cfg.SPORTS_API_BASE || cfg.BACKEND_BASE || "/api").replace(/\/$/, "");
  const DEFAULTS = { nba:"2026-27", nfl:"2026", mlb:"2026", nhl:"2026-27" };
  const state = { sport:"nba", season:DEFAULTS.nba, stage:"Regular Season", date:"", games:[], selectedGame:null, gameTimer:null, scheduleTimer:null, user:null, posts:[], store:[], entitlements:[], checkout:null, xp:0, wagers:[], stripePublishableKey:cfg.STRIPE_PUBLISHABLE_KEY||"" };
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
  const money=c=>`$${(Number(c||0)/100).toFixed(2)}`;
  const toast=m=>{const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2600)};
  const isLive=g=>g?.live||/LIVE|IN PROGRESS|HALFTIME|Q[1-4]|OT/i.test(String(g?.status||""));

  function showPage(id){const valid=["home","sports","game","feed","store","profile","help"];if(!valid.includes(id))id="home";$$('.page').forEach(p=>p.hidden=p.id!==id);$$('.desktop-nav a,.mobile-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));window.scrollTo({top:0,behavior:"smooth"});}
  async function api(path,opts={}){const r=await fetch(`${API}${path}`,{...opts,headers:{Accept:"application/json","Content-Type":"application/json",...(opts.headers||{})}});if(!r.ok)throw new Error((await r.json().catch(()=>null))?.error||`HTTP ${r.status}`);return r.json();}
  function route(){let raw=location.hash.slice(1)||"home";let [path,q]=raw.split("?");if(path.startsWith("game/")){showPage("game");return loadGame(decodeURIComponent(path.slice(5)));}showPage(path);if(path==="sports")loadSchedule();if(path==="feed")loadFeed();if(path==="store")loadStore();if(path==="profile")loadProfile();if(path==="help")loadHelp();if(path==="home")loadMe();if(q&&path==="store"){const p=new URLSearchParams(q);if(p.get("session_id"))verifyPurchase(p.get("session_id"));}}
  function setApiStatus(text,ok=true){const e=$("#apiStatus");if(e){e.textContent=text;e.classList.toggle("bad",!ok);e.classList.toggle("live",ok&&/LIVE/i.test(text));}}
  function updateSeasonOptions(){const vals={nba:["2026-27","2025-26","2024-25","2023-24","2022-23","2021-22","2020-21","2019-20","2018-19","2017-18","2016-17"],nfl:["2026","2025","2024","2023","2022","2021","2020","2019","2018","2017","2016"],mlb:["2026","2025","2024","2023","2022","2021","2020","2019","2018","2017","2016"],nhl:["2026-27","2025-26","2024-25","2023-24","2022-23","2021-22","2020-21","2019-20","2018-19","2017-18","2016-17"]}[state.sport];if(!vals.includes(state.season))state.season=DEFAULTS[state.sport];const s=$("#seasonSelect");s.innerHTML=vals.map(v=>`<option value="${v}">${v.replace("-","–")}</option>`).join("");s.value=state.season;}
  function setSport(s){state.sport=s;state.season=DEFAULTS[s];state.date="";$("#dateFilter").value="";$$('.sport-tab').forEach(b=>b.classList.toggle('active',b.dataset.sport===s));updateSeasonOptions();loadSchedule();}
  async function loadSchedule(){updateSeasonOptions();setApiStatus("Loading…");$("#schedule").innerHTML=`<div class="loading"><span></span><span></span><span></span><p>Loading the ${esc(state.season)} ${esc(state.sport.toUpperCase())} schedule…</p></div>`;const p=new URLSearchParams({sport:state.sport,season:state.season,stage:state.stage});if(state.date)p.set("date",state.date);try{const d=await api(`/schedule?${p}`);state.games=d.games||[];const live=state.games.some(isLive);setApiStatus(live?"LIVE DATA":"DATA CONNECTED");renderSchedule();clearInterval(state.scheduleTimer);if(live)state.scheduleTimer=setInterval(loadSchedule,30000);}catch(e){setApiStatus("DATA OFFLINE",false);$("#schedule").innerHTML=`<div class="empty"><strong>Couldn’t load the schedule.</strong><p>${esc(e.message)}</p><button class="btn btn-primary" id="retrySchedule">Retry</button></div>`;$("#retrySchedule").onclick=loadSchedule;}}
  function renderSchedule(){const games=[...state.games].sort((a,b)=>String(a.date||"").localeCompare(String(b.date||"")));$("#scheduleCount").textContent=`${games.length.toLocaleString()} game${games.length===1?"":"s"} · ${state.season} · ${state.stage}`;if(!games.length){$("#schedule").innerHTML=`<div class="empty"><strong>No games found.</strong><p>Try another date, stage or season.</p></div>`;return;}const groups=new Map();games.forEach(g=>{const d=(g.date||"").slice(0,10)||"Unknown";if(!groups.has(d))groups.set(d,[]);groups.get(d).push(g)});$("#schedule").innerHTML=[...groups].map(([d,list])=>`<section class="date-group"><div class="date-heading"><div><span>${formatDate(d)}</span><small>${list.length} game${list.length===1?"":"s"}</small></div></div>${list.map(gameRow).join("")}</section>`).join("");}
  function gameRow(g){const live=isLive(g);return `<button class="game-row ${live?"is-live":""}" data-game="${esc(g.id)}"><div class="time-col"><strong>${formatTime(g.date)}</strong><span class="status-mini ${live?"live":""}">${esc(g.status||"Scheduled")}</span></div><div class="matchup"><div><small>${esc(g.away?.abbreviation||"")}</small><strong>${esc(g.away?.name||"Away")}</strong></div><span>@</span><div><small>${esc(g.home?.abbreviation||"")}</small><strong>${esc(g.home?.name||"Home")}</strong></div></div><div class="score-col"><b>${g.away?.score??"—"}</b><b>${g.home?.score??"—"}</b></div><span class="chev">${live?"LIVE →":"→"}</span></button>`;}
  function formatDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return s;return new Intl.DateTimeFormat(undefined,{weekday:"long",month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${s}T00:00:00Z`));}
  function formatTime(s){if(!s)return"—";const d=new Date(s);return Number.isNaN(d.getTime())?String(s).slice(11,16):new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"}).format(d);}
  async function loadGame(id){clearInterval(state.gameTimer);state.selectedGame=id;["overviewView","playsView","boxView","chatView"].forEach(x=>$("#"+x).innerHTML=`<div class='loading'><span></span><span></span><span></span><p>Loading Game Center…</p></div>`);try{const data=await api(`/games/${encodeURIComponent(id)}?sport=${encodeURIComponent(state.sport)}`);renderGame(data);if(data.live)state.gameTimer=setInterval(()=>refreshGame(id),12000);}catch(e){$("#overviewView").innerHTML=`<div class="empty"><strong>Game data unavailable.</strong><p>${esc(e.message)}</p><a class="btn btn-primary" href="#sports">Back to schedule</a></div>`;}}
  async function refreshGame(id){try{const d=await api(`/games/${encodeURIComponent(id)}?sport=${encodeURIComponent(state.sport)}&live=1`);renderGame(d);if(!d.live)clearInterval(state.gameTimer)}catch{}}
  function renderGame(g){const a=g.away||{},h=g.home||{};$("#awayCity").textContent=a.shortName||a.abbreviation||"Away";$("#awayName").textContent=a.name||"Away";$("#awayScore").textContent=a.score??"—";$("#homeCity").textContent=h.shortName||h.abbreviation||"Home";$("#homeName").textContent=h.name||"Home";$("#homeScore").textContent=h.score??"—";$("#gameStatus").textContent=(g.status||"FINAL").toUpperCase();$("#gameClock").textContent=g.clock||"";$("#gameArena").textContent=g.venue||"Game Center";$("#gameDate").textContent=g.date?new Date(g.date).toLocaleString():"";$("#playCount").textContent=(g.plays||[]).length.toLocaleString();$("#gameStage").textContent=g.live?"LIVE GAME CENTER":`${g.sport?.toUpperCase()||state.sport.toUpperCase()} GAME CENTER`;const closed=['final','post'].includes(String(g.state||'').toLowerCase());$("#overviewView").innerHTML=`<div class="overview-grid"><article class="info-card"><span class="eyebrow">MAIN FEED</span><h3>${esc(a.name)} ${esc(a.score??"—")} <span>—</span> ${esc(h.name)} ${esc(h.score??"—")}</h3><p class="muted">${esc(g.status)} · ${esc(g.date||"")}</p><div class="game-feed">${renderFeed(g.plays||[])}</div></article><article class="info-card"><span class="eyebrow">GAME DATA</span><div class="metric-grid"><div><b>${(g.plays||[]).length.toLocaleString()}</b><small>events</small></div><div><b>${esc(g.season||state.season)}</b><small>season</small></div><div><b>${esc(g.stage||state.stage)}</b><small>stage</small></div></div>${g.broadcast?`<p class="muted broadcast">${esc(g.broadcast)}</p>`:""}</article></div><article class="info-card wager-card"><div class="wager-head"><div><span class="eyebrow">RUSHRUSH WAGERING</span><h3>Play the game with Rush Coins</h3><p class="muted">Virtual currency only. No cash value or cash-out. ${g.live?'Live wagering is open.':'Pregame wagering is open.'}</p></div><div class="wager-balance">◈ <b id="wagerCoins">${Number(state.user?.coins||0).toLocaleString()}</b></div></div>${closed?`<div class="wager-closed">Wagering closed — this game is final.</div>`:`<div class="wager-options"><button class="wager-choice" data-wager-choice="away"><span>${esc(a.abbreviation||'AWAY')}</span><b>${esc(a.name||'Away')}</b><small>${g.live?'Live odds':'Pregame odds'} · ${g.live?'1.75×':'1.90×'}</small></button><button class="wager-choice" data-wager-choice="home"><span>${esc(h.abbreviation||'HOME')}</span><b>${esc(h.name||'Home')}</b><small>${g.live?'Live odds':'Pregame odds'} · ${g.live?'1.75×':'1.90×'}</small></button></div><div class="wager-form"><label>Rush Coins<input id="wagerStake" type="number" min="10" max="100000" step="10" value="100"></label><button class="btn btn-primary" id="placeWager" type="button" disabled>Choose a team</button></div><small class="muted">Minimum 10 · Maximum 100,000 · payout includes your stake</small>`}</article>`;renderPlays(g.plays||[]);renderBox(g.boxScore||{});renderChat();bindWager(g);loadWagers();}
  function renderFeed(plays){const r=plays.slice(-18).reverse();return r.length?r.map(p=>`<div class="feed-event"><time>${esc(p.clock||"")}</time><span>${esc(p.description||p.text||"")}</span><b>${esc(p.score||"")}</b></div>`).join(""):`<p class="muted">No event feed is available for this game.</p>`;}
  function renderPlays(plays){if(!plays.length){$("#playsView").innerHTML=`<div class="empty"><strong>No play-by-play returned.</strong><p>The provider did not expose an event stream for this game.</p></div>`;return;}const grouped=new Map();plays.forEach(p=>{const q=p.period??1;if(!grouped.has(q))grouped.set(q,[]);grouped.get(q).push(p)});$("#playsView").innerHTML=`<div class="plays-toolbar"><div><span class="eyebrow">ALL PLAYS</span><h3>Complete event stream</h3></div><span>${plays.length.toLocaleString()} events</span></div>${[...grouped].map(([q,ps])=>`<section class="quarter"><div class="quarter-head"><b>${q>4?`OT ${q-4}`:`Q${q}`}</b><span>${ps.length} events</span></div>${ps.map(p=>`<div class="play ${p.scoring?"scoring":""}"><time>${esc(p.clock||"")}</time><div><b>${esc(p.teamTricode||"")}</b><p>${esc(p.description||"")}</p></div><strong>${esc(p.score||"")}</strong></div>`).join("")}</section>`).join("")}`;}
  function renderBox(box){const rows=Array.isArray(box.players)?box.players:[];$("#boxView").innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Player</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th></tr></thead><tbody>${rows.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.team)}</small></td><td>${esc(p.min??"—")}</td><td>${esc(p.pts??"—")}</td><td>${esc(p.reb??"—")}</td><td>${esc(p.ast??"—")}</td><td>${esc(p.stl??"—")}</td><td>${esc(p.blk??"—")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><strong>Box score not supplied.</strong><p>Playrush keeps missing statistics honest.</p></div>`;}
  function renderChat(){const list=state.chat||[];$("#chatView").innerHTML=`<div class="chat-card"><div class="chat-list" id="chatList">${list.map(m=>`<div class="chat-message"><b>${esc(m.user)}</b><span>${esc(m.text)}</span></div>`).join("")||`<div class="chat-message"><b>@playrush</b><span>You're in the Game Center.</span></div>`}</div><form id="chatForm" class="chat-form"><input id="chatInput" maxlength="180" placeholder="Say something…" required><button class="btn btn-primary">Send</button></form></div>`;$("#chatForm").onsubmit=e=>{e.preventDefault();const i=$("#chatInput"),v=i.value.trim();if(!v)return;state.chat=[...(state.chat||[]),{user:`@${state.user?.handle||"you"}`,text:v}];renderChat();};}

  function bindWager(g){let selection=null;const buttons=$$('.wager-choice');buttons.forEach(b=>b.onclick=()=>{selection=b.dataset.wagerChoice;buttons.forEach(x=>x.classList.toggle('selected',x===b));const place=$("#placeWager");if(place)place.disabled=false;if(place)place.textContent=`Wager ${selection==='home'?(g.home?.abbreviation||'HOME'):(g.away?.abbreviation||'AWAY')}`;});const place=$("#placeWager");if(place)place.onclick=async()=>{const stake=Math.floor(Number($("#wagerStake")?.value));if(!selection||!Number.isInteger(stake)){toast('Choose a team and valid Rush Coin amount.');return;}try{const d=await api('/wagers',{method:'POST',body:JSON.stringify({sport:g.sport||state.sport,gameId:g.id,selection,stake})});state.user.coins=d.coins;syncWallet();toast(`Wager placed · ${stake.toLocaleString()} Rush Coins`);await loadWagers();const b=$("#wagerCoins");if(b)b.textContent=Number(d.coins).toLocaleString();}catch(e){toast(e.message)}};}
  async function loadWagers(){try{const d=await api('/wagers');state.wagers=d.wagers||[];const target=$("#wagerHistory");if(target)renderWagerHistory(target,state.wagers);const coins=$("#profileWagerCoins");if(coins)coins.textContent=Number(d.coins||0).toLocaleString();}catch{}}
  function renderWagerHistory(target,wagers){target.innerHTML=wagers.length?wagers.map(w=>`<div class="wager-history-row"><div><b>${esc(String(w.selection).toUpperCase())}</b><span>${esc(w.sport?.toUpperCase()||'')} · ${esc(w.gameId)}</span></div><div><strong>${Number(w.stake).toLocaleString()} ◈</strong><small>${esc(w.status||'open')} · ${Number(w.odds).toFixed(2)}×</small></div></div>`).join(''):`<div class="empty"><strong>No wagers yet.</strong><p>Open a future or live game and use Rush Coins to make a prediction.</p></div>`;}

  async function loadMe(){try{if(!state.stripePublishableKey){const c=await api('/config').catch(()=>({}));state.stripePublishableKey=c.stripePublishableKey||state.stripePublishableKey;}state.user=await api('/me');syncWallet();}catch{}}
  function syncWallet(){const coins=state.user?.coins||0;$("#coinBalance").textContent=coins.toLocaleString();$("#profileCoins").textContent=coins.toLocaleString();$("#storeWallet").textContent=coins.toLocaleString();$("#profileHandle").textContent=`@${state.user?.handle||"fan"}`;$("#profileEmail").value=state.user?.email||"";$("#handleInput").value=state.user?.handle||"";$("#xp").textContent=(state.user?.xp||0).toLocaleString();}
  async function loadProfile(){await loadMe();await loadWagers();$("#entitlementList").innerHTML=(state.user?.entitlements||[]).length?state.user.entitlements.map(x=>`<span class="entitlement">${esc(x)}</span>`).join(""):"<span class='muted'>No premium unlocks yet.</span>";}
  async function loadHelp(){const status=$("#supportStatus");if(status)status.textContent="Support is ready. For account-specific issues, submit a request below.";}
  async function submitSupport(){const subject=$("#supportSubject").value.trim(),message=$("#supportMessage").value.trim();if(!subject||!message)return;try{const d=await api('/support',{method:'POST',body:JSON.stringify({subject,message})});$("#supportForm").reset();$("#supportStatus").textContent=`Request ${d.ticketId} submitted. We’ll keep it attached to your Playrush profile.`;toast('Support request sent');}catch(e){$("#supportStatus").textContent=e.message;toast(e.message)}}
  async function checkSystemStatus(){const b=$("#checkStatus");if(b)b.disabled=true;try{const d=await api('/health');const ok=d.ok&&d.sportsProvider;toast(`Playrush is online · database ${d.database?'connected':'local fallback'} · payments ${d.payments?'configured':'not configured'}`);if(b)b.textContent=ok?'System online':'Check complete';}catch(e){toast('Unable to reach Playrush services');if(b)b.textContent='Status unavailable';}finally{if(b)setTimeout(()=>{b.disabled=false;b.textContent='Check system status'},2500);}}

  async function loadFeed(){try{const d=await api('/feed');state.posts=d.posts||[];renderPosts();}catch(e){$("#posts").innerHTML=`<div class="empty"><strong>Feed unavailable.</strong><p>${esc(e.message)}</p></div>`;}}
  function renderPosts(){$("#posts").innerHTML=state.posts.map((p,i)=>`<article class="post"><div class="post-head"><div class="avatar">P</div><div><b>${esc(p.user)}</b><small>Community</small></div></div><p>${esc(p.text)}</p><div class="post-actions"><button type="button" data-like="${esc(p.id||i)}">♡ ${p.likes||0}</button><button type="button" data-reply>↩ Reply</button><button type="button" data-share>↗ Share</button></div></article>`).join("")||`<div class="empty"><strong>Be the first voice.</strong><p>Post what you're watching.</p></div>`;}
  async function submitPost(){const i=$("#postInput"),v=i.value.trim();if(!v)return;try{await api('/feed',{method:'POST',body:JSON.stringify({body:v})});i.value="";await loadFeed();toast("Posted to Playrush");}catch(e){toast(e.message)}}
  async function likePost(id){try{await api(`/feed/${encodeURIComponent(id)}/like`,{method:'POST'});await loadFeed();}catch(e){toast(e.message)}}

  async function loadStore(){try{const d=await api('/store');state.store=d.items||[];state.entitlements=d.entitlements||{};syncWalletFromStore(d);renderStore(d);if(!d.stripeConfigured)$("#storeNotice").textContent=d.setupMessage;}catch(e){$("#storeGrid").innerHTML=`<div class="empty"><strong>Store unavailable.</strong><p>${esc(e.message)}</p></div>`;}}
  function syncWalletFromStore(d){if(state.user){state.user.coins=d.coins;syncWallet();}}
  function renderStore(d){$("#storeStatus").textContent=d.stripeConfigured?"SECURE CHECKOUT ENABLED":"PAYMENTS NEED CONFIGURATION";$("#storeStatus").classList.toggle('bad',!d.stripeConfigured);$("#storeGrid").innerHTML=state.store.map(p=>`<article class="store-card accent-${esc(p.accent||'blue')}"><div class="store-art"><span>${p.type==='coins'?'◈':'✦'}</span></div><div class="store-copy"><span class="store-category">${esc(p.category)}</span><h3>${esc(p.name)}</h3><p>${esc(p.description)}</p>${p.badge?`<b class="store-badge">${esc(p.badge)}</b>`:""}<div class="store-buy"><strong>${money(p.amount)}</strong><div class="store-buy-actions">${p.coinPrice?`<button class="btn btn-ghost" data-redeem="${esc(p.id)}">◈ ${Number(p.coinPrice).toLocaleString()}</button>`:""}<button class="btn btn-primary" data-buy="${esc(p.id)}" ${d.stripeConfigured?'':'disabled'}>${d.stripeConfigured?'Buy now':'Unavailable'}</button></div></div></div></article>`).join("");}

  async function redeemItem(productId){try{const d=await api('/store/redeem',{method:'POST',body:JSON.stringify({productId})});state.user=d.user;syncWallet();await loadStore();await loadProfile();toast('Unlocked on your Playrush profile');}catch(e){toast(e.message)}}
  async function startCheckout(productId){try{const d=await api('/store/checkout',{method:'POST',body:JSON.stringify({productId})});if(!window.Stripe){toast('Stripe.js failed to load');return;}if(state.checkout){try{state.checkout.destroy();}catch{}}const stripe=window.Stripe(state.stripePublishableKey||window.PLAYRUSH_CONFIG?.STRIPE_PUBLISHABLE_KEY||'');if(!stripe){toast('Stripe publishable key is not configured');return;}state.checkout=await stripe.initEmbeddedCheckout({fetchClientSecret:async()=>d.clientSecret});$("#checkoutModal").hidden=false;$("#checkoutMount").innerHTML="";state.checkout.mount('#checkoutMount');}catch(e){toast(e.message)}}
  async function verifyPurchase(sessionId){try{const d=await api(`/store/session/${encodeURIComponent(sessionId)}`);if(d.paymentStatus==='paid'){toast('Payment complete. Your purchase is being added to your Playrush wallet.');setTimeout(()=>{loadMe();loadStore()},1200);}}catch(e){toast(e.message)}}

  $$('.sport-tab').forEach(b=>b.onclick=()=>setSport(b.dataset.sport));
  $("#seasonSelect").onchange=e=>{state.season=e.target.value;loadSchedule()};$("#stageSelect").onchange=e=>{state.stage=e.target.value;loadSchedule()};$("#dateFilter").onchange=e=>{state.date=e.target.value;loadSchedule()};$("#clearDate").onclick=()=>{state.date="";$("#dateFilter").value="";loadSchedule()};
  $("#prevDay").onclick=()=>shiftDate(-1);$("#nextDay").onclick=()=>shiftDate(1);$("#todayBtn").onclick=()=>{state.date=new Date().toISOString().slice(0,10);$("#dateFilter").value=state.date;loadSchedule()};
  $("#schedule").onclick=e=>{const b=e.target.closest('[data-game]');if(b){state.sport=state.sport;location.hash=`game/${encodeURIComponent(b.dataset.game)}`}};
  $$('.game-side').forEach(b=>b.onclick=()=>{const v=b.dataset.gameView;$$('.game-side').forEach(x=>x.classList.toggle('active',x===b));['overview','plays','box','chat'].forEach(x=>$("#"+x+'View').hidden=x!==v)});
  $("#postForm").onsubmit=e=>{e.preventDefault();submitPost()};$("#posts").onclick=e=>{const l=e.target.closest('[data-like]');if(l)likePost(l.dataset.like);};
  $("#storeGrid").onclick=e=>{const b=e.target.closest('[data-buy]');const r=e.target.closest('[data-redeem]');if(b)startCheckout(b.dataset.buy);if(r)redeemItem(r.dataset.redeem)};$("#closeCheckout").onclick=()=>{$("#checkoutModal").hidden=true;if(state.checkout){try{state.checkout.destroy()}catch{}}state.checkout=null};
  $("#supportForm").onsubmit=e=>{e.preventDefault();submitSupport()};$("#checkStatus").onclick=checkSystemStatus;
  $("#profileForm").onsubmit=async e=>{e.preventDefault();try{state.user=await api('/me',{method:'PATCH',body:JSON.stringify({handle:$("#handleInput").value,email:$("#profileEmail").value})});syncWallet();toast('Profile saved')}catch(err){toast(err.message)}};
  $("#billingPortal").onclick=async()=>{try{const d=await api('/store/portal',{method:'POST'});location.href=d.url}catch(e){toast(e.message)}};
  $("#mobileMenu").onclick=()=>{const n=$("#mobileNav"),open=n.hidden;n.hidden=!open;$("#mobileMenu").setAttribute('aria-expanded',String(open))};$$('.mobile-nav a').forEach(a=>a.onclick=()=>$("#mobileNav").hidden=true);
  function shiftDate(n){const d=state.date?new Date(`${state.date}T00:00:00Z`):new Date();d.setUTCDate(d.getUTCDate()+n);state.date=d.toISOString().slice(0,10);$("#dateFilter").value=state.date;loadSchedule()}
  window.addEventListener('hashchange',route);updateSeasonOptions();loadMe();route();
})();
