(() => {
  "use strict";
  const cfg = window.PLAYRUSH_CONFIG || {};
  const API = String(cfg.SPORTS_API_BASE || cfg.BACKEND_BASE || "/api").replace(/\/$/, "");
  const state = { sport:"nba", season:"2016-17", stage:"Regular Season", date:"", games:[], selectedGame:null, coins:1250, xp:0, posts:[
    {user:"@playrush", text:"Welcome to Playrush — historical games and live-ready Game Center.", likes:12},
    {user:"@gamecenter", text:"Every game has an Overview, full Play-by-Play, Box Score and Live Chat.", likes:8}
  ], predictions:[{id:"p1",away:"Pistons",home:"Bulls",awayMod:-.76,homeMod:.24},{id:"p2",away:"Lions",home:"Bears",awayMod:.10,homeMod:.05}]};
  const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  const toast=m=>{const e=$("#toast");e.textContent=m;e.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>e.classList.remove("show"),2400)};
  function route(){let raw=location.hash.slice(1)||"home";let [path,q]=raw.split("?");if(path.startsWith("game/")){showPage("game");return loadGame(path.slice(5));} showPage(path||"home"); if(q){const p=new URLSearchParams(q);if(path==="sports"&&p.get("season")){state.season=p.get("season");$("#seasonSelect").value=state.season;loadSchedule()}}}
  function showPage(id){const valid=["home","sports","game","predictions","feed","profile"];if(!valid.includes(id))id="home";$$('.page').forEach(p=>p.hidden=p.id!==id);$$('.desktop-nav a,.mobile-nav a').forEach(a=>a.classList.toggle('active',a.getAttribute('href')===`#${id}`));window.scrollTo({top:0,behavior:"smooth"})}
  async function api(path,opts={}){const r=await fetch(`${API}${path}`,{...opts,headers:{Accept:"application/json",...(opts.headers||{})}});if(!r.ok)throw new Error((await r.text().catch(()=>""))||`HTTP ${r.status}`);return r.json()}
  function setApiStatus(text,ok=true){const e=$("#apiStatus");e.textContent=text;e.classList.toggle("bad",!ok)}
  async function loadSchedule(){
    state.sport=state.sport.toLowerCase(); setApiStatus("Loading data…"); $("#schedule").innerHTML=`<div class="loading"><span></span><span></span><span></span><p>Loading ${esc(state.season)} schedule…</p></div>`;
    const params=new URLSearchParams({sport:state.sport,season:state.season,stage:state.stage}); if(state.date)params.set("date",state.date);
    try{const data=await api(`/schedule?${params}`);state.games=Array.isArray(data.games)?data.games:[];setApiStatus("DATA CONNECTED");renderSchedule()}catch(e){setApiStatus("DATA OFFLINE",false);$("#schedule").innerHTML=`<div class="empty"><strong>Couldn’t load the schedule.</strong><p>${esc(e.message)}</p><button class="btn btn-primary" id="retrySchedule" type="button">Retry</button><small>Run the included Node server or point config.js at your sports backend.</small></div>`;$("#retrySchedule").onclick=loadSchedule}
  }
  function renderSchedule(){
    const games=[...state.games].sort((a,b)=>String(a.date||"").localeCompare(String(b.date||"")));$("#scheduleCount").textContent=`${games.length.toLocaleString()} game${games.length===1?"":"s"} · ${state.season} · ${state.stage}`;
    if(!games.length){$("#schedule").innerHTML=`<div class="empty"><strong>No games found.</strong><p>Try another date, stage or season.</p></div>`;return}
    const groups=new Map();games.forEach(g=>{const d=(g.date||"").slice(0,10)||"Unknown date";(groups.get(d)||groups.set(d,[]).get(d)).push(g)});
    $("#schedule").innerHTML=[...groups].map(([date,list])=>`<section class="date-group"><div class="date-heading"><div><span>${formatDate(date)}</span><small>${list.length} game${list.length===1?"":"s"}</small></div></div>${list.map(gameRow).join("")}</section>`).join("");
    $$("[data-game-id]").forEach(b=>b.onclick=()=>{location.hash=`game/${encodeURIComponent(b.dataset.gameId)}`});
  }
  function gameRow(g){const status=(g.status||"Scheduled").toUpperCase();const live=/LIVE|PROGRESS|INPROGRESS/.test(status);return `<button class="game-row" data-game-id="${esc(g.gameId)}" type="button"><div class="time-col"><b>${formatTime(g.date)}</b><span class="status-mini ${live?'live':''}">${esc(g.status||"Scheduled")}</span></div><div class="matchup"><div><strong>${esc(g.away?.name||g.awayName||g.away||"Away")}</strong><small>${esc(g.away?.record||"")}</small></div><b>@</b><div><strong>${esc(g.home?.name||g.homeName||g.home||"Home")}</strong><small>${esc(g.home?.record||"")}</small></div></div><div class="score-col"><b>${g.away?.score??g.awayScore??"—"}</b><b>${g.home?.score??g.homeScore??"—"}</b></div><span class="chev">→</span></button>`}
  function formatDate(s){if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return s;return new Intl.DateTimeFormat(undefined,{weekday:"long",month:"short",day:"numeric",year:"numeric",timeZone:"UTC"}).format(new Date(`${s}T00:00:00Z`))}
  function formatTime(s){if(!s)return"—";const d=new Date(s);return Number.isNaN(d.getTime())?String(s).slice(11,16):new Intl.DateTimeFormat(undefined,{hour:"numeric",minute:"2-digit",timeZone:"America/New_York"}).format(d)}
  async function loadGame(id){
    state.selectedGame=id; $("#gameStage").textContent="GAME CENTER";["overviewView","playsView","boxView","chatView"].forEach(id=>{$("#"+id).innerHTML="<div class='loading'><span></span><span></span><span></span><p>Loading game data…</p></div>"});
    try{const data=await api(`/games/${encodeURIComponent(id)}?sport=${encodeURIComponent(state.sport)}`);renderGame(data)}catch(e){$("#overviewView").innerHTML=`<div class="empty"><strong>Game data unavailable.</strong><p>${esc(e.message)}</p><a class="btn btn-primary" href="#sports">Back to schedule</a></div>`}
  }
  function renderGame(g){
    const a=g.away||{},h=g.home||{};$("#awayCity").textContent=a.city||"Away";$("#awayName").textContent=a.name||a.abbreviation||"Away";$("#awayScore").textContent=a.score??"—";$("#homeCity").textContent=h.city||"Home";$("#homeName").textContent=h.name||h.abbreviation||"Home";$("#homeScore").textContent=h.score??"—";$("#gameStatus").textContent=(g.status||"FINAL").toUpperCase();$("#gameClock").textContent=g.clock||"";$("#gameArena").textContent=g.arena||"Historical game";$("#gameDate").textContent=g.date?formatDate(g.date.slice(0,10)):"";$("#playCount").textContent=(g.plays||[]).length.toLocaleString();
    $("#overviewView").innerHTML=`<div class="overview-grid"><article class="info-card"><span class="eyebrow">GAME SUMMARY</span><h3>${esc(a.name||"Away")} ${esc(a.score??"—")} <span>—</span> ${esc(h.name||"Home")} ${esc(h.score??"—")}</h3><p class="muted">${esc(g.status||"Final")} · ${esc(g.date||"")}</p></article><article class="info-card"><span class="eyebrow">GAME DATA</span><div class="metric-grid"><div><b>${(g.plays||[]).length.toLocaleString()}</b><small>plays</small></div><div><b>${esc(g.season||state.season)}</b><small>season</small></div><div><b>${esc(g.stage||state.stage)}</b><small>stage</small></div></div></article></div>${g.note?`<div class="notice">${esc(g.note)}</div>`:""}`;
    renderPlays(g.plays||[]);renderBox(g.boxScore||{});renderChat();
  }
  function renderPlays(plays){if(!plays.length){$("#playsView").innerHTML=`<div class="empty"><strong>No play-by-play returned for this game.</strong><p>The schedule exists, but this data source does not expose an event stream for this game.</p></div>`;return}const grouped=new Map();plays.forEach(p=>{const q=p.period??p.quarter??1;(grouped.get(q)||grouped.set(q,[]).get(q)).push(p)});$("#playsView").innerHTML=`<div class="plays-toolbar"><div><span class="eyebrow">ALL PLAYS</span><h3>Complete event stream</h3></div><span>${plays.length.toLocaleString()} events</span></div>${[...grouped].map(([q,ps])=>`<section class="quarter"><div class="quarter-head"><b>${q>4?`OT ${q-4}`:`Q${q}`}</b><span>${ps.length} events</span></div>${ps.map(p=>`<div class="play"><time>${esc(p.clock||p.time||"")}</time><div><b>${esc(p.teamTricode||p.team||"")}</b><p>${esc(p.description||p.text||"")}</p></div><strong>${esc(p.score||((p.scoreAway!=null&&p.scoreHome!=null)?`${p.scoreAway}–${p.scoreHome}`:""))}</strong></div>`).join("")}</section>`).join("")}`}
  function renderBox(box){const rows=Array.isArray(box.players)?box.players:[];$("#boxView").innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr><th>Player</th><th>MIN</th><th>PTS</th><th>REB</th><th>AST</th><th>STL</th><th>BLK</th></tr></thead><tbody>${rows.map(p=>`<tr><td><b>${esc(p.name)}</b><small>${esc(p.team||"")}</small></td><td>${esc(p.min??"—")}</td><td>${esc(p.pts??"—")}</td><td>${esc(p.reb??"—")}</td><td>${esc(p.ast??"—")}</td><td>${esc(p.stl??"—")}</td><td>${esc(p.blk??"—")}</td></tr>`).join("")}</tbody></table></div>`:`<div class="empty"><strong>Box score not supplied.</strong><p>This Game Center keeps the section honest rather than inventing player statistics.</p></div>`}
  function renderChat(){$("#chatView").innerHTML=`<div class="chat-card"><div class="chat-list" id="chatList"><div class="chat-message"><b>@playrush</b><span>Game chat is ready.</span></div></div><form id="chatForm" class="chat-form"><input id="chatInput" maxlength="180" placeholder="Say something…" required><button class="btn btn-primary">Send</button></form></div>`;$("#chatForm").onsubmit=e=>{e.preventDefault();const i=$("#chatInput"),v=i.value.trim();if(!v)return;$("#chatList").insertAdjacentHTML("beforeend",`<div class="chat-message"><b>@you</b><span>${esc(v)}</span></div>`);i.value=""}}
  function renderPosts(){$("#posts").innerHTML=state.posts.map((p,i)=>`<article class="post"><div class="post-head"><div class="avatar">P</div><div><b>${esc(p.user)}</b><small>Just now · Community</small></div></div><p>${esc(p.text)}</p><div class="post-actions"><button type="button" data-like="${i}">♡ ${p.likes}</button><button type="button" data-reply="${i}">↩ Reply</button><button type="button" data-share="${i}">↗ Share</button></div></article>`).join("")}
  function renderPredictions(){$("#predictionCards").innerHTML=state.predictions.map(p=>`<article class="prediction"><div class="pred-head"><div><small>XP MODIFIER</small><h3>${esc(p.away)} <span>vs</span> ${esc(p.home)}</h3></div><span class="pred-badge">100 XP BASE</span></div><div class="pred-choices"><button data-pick="${p.id}" data-team="${esc(p.away)}" type="button"><b>${esc(p.away)}</b><span>${p.awayMod<0?`${Math.round(Math.abs(p.awayMod)*100)}% lower`: `${Math.round(p.awayMod*100)}% higher`} reward</span></button><button data-pick="${p.id}" data-team="${esc(p.home)}" type="button"><b>${esc(p.home)}</b><span>${p.homeMod<0?`${Math.round(Math.abs(p.homeMod)*100)}% lower`: `${Math.round(p.homeMod*100)}% higher`} reward</span></button></div></article>`).join("")}
  function coins(){ $("#coinBalance").textContent=state.coins.toLocaleString();$("#profileCoins").textContent=state.coins.toLocaleString();$("#xp").textContent=state.xp.toLocaleString() }
  $$(".sport-tab").forEach(b=>b.onclick=()=>{$$(".sport-tab").forEach(x=>x.classList.toggle("active",x===b));state.sport=b.dataset.sport;loadSchedule()});$("#seasonSelect").onchange=e=>{state.season=e.target.value;loadSchedule()};$("#stageSelect").onchange=e=>{state.stage=e.target.value;loadSchedule()};$("#dateFilter").onchange=e=>{state.date=e.target.value;loadSchedule()};$("#clearDate").onclick=()=>{$("#dateFilter").value="";state.date="";loadSchedule()};$("#prevDay").onclick=()=>shiftDate(-1);$("#nextDay").onclick=()=>shiftDate(1);$("#todayBtn").onclick=()=>{$("#dateFilter").value=new Date().toISOString().slice(0,10);state.date=$("#dateFilter").value;loadSchedule()};
  function shiftDate(n){const d=state.date?new Date(`${state.date}T00:00:00Z`):new Date();d.setUTCDate(d.getUTCDate()+n);state.date=d.toISOString().slice(0,10);$("#dateFilter").value=state.date;loadSchedule()}
  $$(".game-side").forEach(b=>b.onclick=()=>{const v=b.dataset.gameView;$$('.game-side').forEach(x=>x.classList.toggle('active',x===b));['overview','plays','box','chat'].forEach(x=>$("#"+x+"View").hidden=x!==v)});
  $("#postForm").onsubmit=e=>{e.preventDefault();const i=$("#postInput"),v=i.value.trim();if(!v)return;state.posts.unshift({user:"@playrushzii",text:v,likes:0});i.value="";renderPosts();toast("Posted")};$("#posts").onclick=e=>{const l=e.target.closest('[data-like]');const r=e.target.closest('[data-reply]');const s=e.target.closest('[data-share]');if(l){state.posts[+l.dataset.like].likes++;renderPosts()}if(r)toast("Reply composer coming with backend social API.");if(s)toast("Share action ready.")};$("#predictionCards").onclick=e=>{const b=e.target.closest('[data-pick]');if(!b)return;const p=state.predictions.find(x=>x.id===b.dataset.pick);const mod=b.dataset.team===p.away?p.awayMod:p.homeMod;const reward=Math.max(1,Math.round(100*(1+mod)));toast(`${b.dataset.team} selected · ${reward} XP potential`);state.xp+=5;coins()};
  $("#mobileMenu").onclick=()=>{const n=$("#mobileNav"),open=n.hidden;n.hidden=!open;$("#mobileMenu").setAttribute("aria-expanded",String(open))};$$('.mobile-nav a').forEach(a=>a.onclick=()=>{$("#mobileNav").hidden=true});$("#coinPill").onclick=()=>{toast(`Balance: ${state.coins.toLocaleString()} coins`)};
  window.addEventListener("hashchange",route);renderPosts();renderPredictions();coins();route();
  if(location.hash==="#sports"||location.hash==="")loadSchedule();
})();
